// <auto-generated />
namespace ECC.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class campopalavrachafrom100to1000 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campopalavrachafrom100to1000));
        
        string IMigrationMetadata.Id
        {
            get { return "201906012043466_campo palavracha from 100 to 1000"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
