// <auto-generated />
namespace ECC.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateemdev : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateemdev));
        
        string IMigrationMetadata.Id
        {
            get { return "201907222212172_update em dev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
